EUREKA_HOST: 172.18.21.175
EUREKA_PORT: 22001
SERVER_PORT: 22002
spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  instance:
      hostname: eureka-server
      status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:22001}/eureka/
server:
  port: ${SERVER_PORT:22001}

logging:
  path: /var/log/hotel-eureka/
  file: inf-eureka.log